###
GET https://www.dnd5eapi.co/api/

###
GET https://www.dnd5eapi.co/api/classes

###
GET https://www.dnd5eapi.co/api/classes/monk

###
GET https://www.dnd5eapi.co/api/rules

###
GET https://www.dnd5eapi.co/api/rule-sections
###
GET https://www.dnd5eapi.co/api/ability-scores
###
GET https://www.dnd5eapi.co/api/races
###
GET https://www.dnd5eapi.co/api/races/dragonborn
###
GET https://www.dnd5eapi.co/api/races/elf
###
GET https://www.dnd5eapi.co/api/backgrounds
###
GET https://www.dnd5eapi.co/api/backgrounds/acolyte
###
GET https://www.dnd5eapi.co/api/classes/fighter
###
GET https://www.dnd5eapi.co/api/subraces/high-elf
###
GET https://www.dnd5eapi.co/api/rules
###
GET https://www.dnd5eapi.co/api/rules/adventuring
###
GET https://www.dnd5eapi.co/api/rule-sections/between-adventures
###
GET https://www.dnd5eapi.co/api/rules/appendix
###
GET https://www.dnd5eapi.co/api/ability-scores/dex
###
GET https://www.dnd5eapi.co/api/traits/darkvision
