###
GET http://localhost:8080/character/getcharacters

###
GET http://localhost:8080/character/getcharacter/35

//character initilize/baseInfo
###
POST http://localhost:8080/buildcharacter/base/
Content-Type: application/json 

{
  "name": "Carson",
  "level": "1",
  "alignment": "test align",
  "proficiencyBonus": 1,
  "experiencePoints": 0
}

//add class to character


###
PUT http://localhost:8080/buildcharacter/class/35
Content-Type: application/json

{
  "name" : "fairy",
  "description": "fairy boi",
    "features": [
    {
      "name" : "something unique",
      "description" :"unique things"
    },
    # Insert Features Here
    {
      "name" : "watch shows faster",
      "description" :" more shows in less time"
    }

  ]
}

###
PUT http://localhost:8080/buildcharacter/editclass/12 
Content-Type: application/json

{
  "name" : "org",
  "description": "org boi",
    "features": [
    {
      "name" : "swim fast",
      "description" :"like running but swimming"
    },
    # Insert Features Here
    {
      "name" : "Become Kickie Ridwell",
      "description" :"True Level up"
    }

  ]
}

###
PUT http://localhost:8080/buildcharacter/race/35
Content-Type: application/json

{
  "name" : "dwarf",
  "description" :"short boi/girl",
  "abilityScoreImprovement1": 2,
  "abilityScoreImprovement2": 1,
  "abilityScoreImprovementName1": "strength",
  "abilityScoreImprovementName2": "charisma",
  "features": [
    {
      "name" : "run fast",
      "description" :"super sonic speed",
      "class" : null,
      "race" : null,
      "background" : null
    },
    # Insert Features Here
    {
      "name" : "CARSON FEATURES HERE",
      "description" :"???????",
      "class" : null,
      "race" : null,
      "background" : null
    }

  ]
}

###
PUT http://localhost:8080/buildcharacter/editrace/17
Content-Type: application/json

{
  "name" : "deamon race",
  "description" :"deamon boi/girl",
  "abilityScoreImprovement1": 2,
  "abilityScoreImprovement2": 0,
  "abilityScoreImprovementName1": "dexterity",
  "abilityScoreImprovementName2": "wisdom",
    "features": [
    {
      "name" : "Stupid Like Britney",
      "description" :"Has zero logic skills"
    },
    # Insert Features Here
    {
      "name" : "Brillaint",
      "description" :"Like Rickie"
    }

  ]
  }


###
PUT http://localhost:8080/buildcharacter/background/35
Content-Type: application/json

{
  "name" : "acolyte",
  "description": "because what else",
  "features" : [
    {
      "name" : "code fast",
      "description" :"super sonic typing"
    },
    # Insert Features Here
    {
      "name" : "Speed reading",
      "description" : "get 'er don"
    }
  ]
}

###
PUT http://localhost:8080/buildcharacter/editbackground/17
Content-Type: application/json

{
  "name" : "gremin",
  "description": "don't put water on me",
  "features" : [
    {
      "name" : "debug fast",
      "description" :"never miss a char"
    },
    # Insert Features Here
    {
      "name" : "logic skills",
      "description" : "break down complex things"
    }
  ]
}
###
PUT http://localhost:8080/buildcharacter/abilityscore/17
Content-Type: application/json

{
  "strength": 12,
  "dexterity": 15,
  "constitution": 14,
  "intelligence": 10,
  "wisdom": 8,
  "charisma": 13
}
###
GET  http://localhost:8080/character/showallfeatures