###
GET https://www.dnd5eapi.co/api/classes

###
GET https://www.dnd5eapi.co/api/classes/wizard/levels

###
GET https://www.dnd5eapi.co/api/features/arcane-recovery

###
GET https://www.dnd5eapi.co/api/rules/spellcasting

###
GET https://www.dnd5eapi.co/api/rules/adventuring
###
GET https://www.dnd5eapi.co/api/ability-scores
###
GET https://www.dnd5eapi.co/api/races
###
GET https://www.dnd5eapi.co/api/races/tiefling
###
GET https://www.dnd5eapi.co/api/traits/infernal-legacy
###
GET https://www.dnd5eapi.co/api/traits/trance
###
GET https://www.dnd5eapi.co/api/backgrounds/acolyte
###
GET https://www.dnd5eapi.co/api/classes/fighter
###
GET https://www.dnd5eapi.co/api/subraces/high-elf
###
GET https://www.dnd5eapi.co/api/rule-sections/the-environment"
###
GET https://www.dnd5eapi.co/api/rule-sections/diseases
###
GET https://www.dnd5eapi.co/api/rule-sections/between-adventures
###
GET https://www.dnd5eapi.co/api/rules/appendix
###
GET https://www.dnd5eapi.co/api/ability-scores/dex
###
GET https://www.dnd5eapi.co/api/traits/darkvision
