###
GET http://localhost:8080/character/getcharacters



//character initilize/baseInfo
###
POST http://localhost:8080/buildcharacter/base/
Content-Type: application/json 

{
  "name": "Carson",
  "level": "1",
  "alignment": "test align",
  "proficiencyBonus": 1,
  "experiencePoints": 0
}

//add class to character


###
PUT http://localhost:8080/buildcharacter/class/9
Content-Type: application/json

{
  "name" : "fairy",
  "description": "fairy boi"
}

###
PUT http://localhost:8080/buildcharacter/editclass/9 
Content-Type: application/json

{
  "name" : "org",
  "description": "org boi"
}

###
PUT http://localhost:8080/buildcharacter/race/13
Content-Type: application/json

{
  "name" : "dwarf",
  "description" :"short boi/girl",
  "features": [
    {
      "name" : "run fast",
      "description" :"super sonic speed"
    },
    # Insert Features Here
    {
      "name" : "CARSON FEATURES HERE",
      "description" :"???????"
    }

  ]
}

###
PUT http://localhost:8080/buildcharacter/editrace/13
Content-Type: application/json

{
  "name" : "deamon race",
  "description" :"deamon boi/girl",
    "features": [
    {
      "name" : "Stupid Like Britney",
      "description" :"Has zero logic skills"
    },
    # Insert Features Here
    {
      "name" : "Brillaint",
      "description" :"Like Rickie"
    }

  ]
  }

###
PUT http://localhost:8080/buildcharacter/background/9
Content-Type: application/json

{
  "name" : "acolyte",
  "description": "because what else"
}

###
PUT http://localhost:8080/buildcharacter/editbackground/9
Content-Type: application/json

{
  "name" : "gremin",
  "description": "don't put water on me"
}


###
GET  http://localhost:8080/character/showallfeatures