###
GET http://localhost:8080/character/getcharacter



//character initilize/baseInfo
###
POST http://localhost:8080/buildcharacter/base/
Content-Type: application/json 

{
  "name": "Carson",
  "level": "1",
  "alignment": "test align",
  "proficiencyBonus": 1,
  "experiencePoints": 0
}

//add class to character
###
PUT http://localhost:8080/buildcharacter/class/9
Content-Type: application/json

{
  "name" : "fairy",
  "description": "fairy boi"
}

###
PUT http://localhost:8080/buildcharacter/editclass/9 
Content-Type: application/json

{
  "name" : "org",
  "description": "org boi"
}

###
PUT http://localhost:8080/buildcharacter/race/9
Content-Type: application/json

{
  "name" : "dwarf",
  "description" :"short boi/girl"
}

###
PUT http://localhost:8080/buildcharacter/editrace/9
Content-Type: application/json

{
  "name" : "deamon race",
  "description" :"deamon boi/girl"
  }

###
PUT http://localhost:8080/buildcharacter/background/9
Content-Type: application/json

{
  "name" : "acolyte",
  "description": "because what else"
}

###
PUT http://localhost:8080/buildcharacter/editbackground/9
Content-Type: application/json

{
  "name" : "gremin",
  "description": "don't put water on me"
}
